<?php

declare(strict_types=1);

namespace IanFoxDev\SloKit;

use Symfony\Component\Yaml\Yaml;

/**
 * Turns the SLO file into a Sloth spec (prometheus/v1). Sloth turns that into recording
 * rules and multi-window, multi-burn-rate alerts. The queries read the metrics the Recorder
 * exports, with the same routes and the same definition of an error.
 *
 * An availability SLO counts responses whose code is in its error list. A latency SLO counts
 * requests slower than its threshold: all requests minus those in the threshold's bucket.
 */
final class SlothSpec
{
    public static function yaml(SloFile $file): string
    {
        return "# Generated by slo-kit from the SLO file; edit that file, not this one.\n"
            . Yaml::dump(self::spec($file), 8, 2, Yaml::DUMP_MULTI_LINE_LITERAL_BLOCK);
    }

    /**
     * @return array{version: string, service: string, labels: array<string, string>, slos: list<array{name: string, objective: float, description: string, sli: array{events: array{error_query: string, total_query: string}}, alerting: array{name: string, labels: array<string, string>, annotations: array<string, string>, page_alert: array{labels: array<string, string>}, ticket_alert: array{labels: array<string, string>}}}>}
     */
    public static function spec(SloFile $file): array
    {
        $names = $file->metricNames();
        $slos = [];
        foreach ($file->slos as $slo) {
            $routes = 'route=~"' . self::routeRegex($slo->routes) . '"';
            if ($slo->threshold === null) {
                $error = \sprintf('sum(rate(%s{%s,code=~"%s"}[{{.window}}]))', $names['requests'], $routes, self::codeRegex($slo->errorStatuses));
                $total = \sprintf('sum(rate(%s{%s}[{{.window}}]))', $names['requests'], $routes);
                $description = \sprintf('%s%% of requests on %s succeed; errors are %s.', self::number($slo->objective), implode(', ', $slo->routes), implode(', ', array_map(strval(...), $slo->errorStatuses)));
            } else {
                $le = self::number($slo->threshold);
                $total = \sprintf('sum(rate(%s_count{%s}[{{.window}}]))', $names['duration'], $routes);
                $error = \sprintf('(%s - sum(rate(%s_bucket{%s,le="%s"}[{{.window}}])))', $total, $names['duration'], $routes, $le);
                $description = \sprintf('%s%% of requests on %s finish within %s ms.', self::number($slo->objective), implode(', ', $slo->routes), self::number($slo->threshold * 1000));
            }
            $slos[] = [
                'name' => $slo->name,
                'objective' => $slo->objective,
                'description' => $description,
                'sli' => ['events' => ['error_query' => $error, 'total_query' => $total]],
                'alerting' => [
                    'name' => self::alertName($file->service, $slo->name),
                    'labels' => ['service' => $file->service, 'slo' => $slo->name],
                    'annotations' => ['summary' => \sprintf('%s is burning its error budget: %s', $file->service, $description)],
                    'page_alert' => ['labels' => ['severity' => 'page']],
                    'ticket_alert' => ['labels' => ['severity' => 'ticket']],
                ],
            ];
        }

        return ['version' => 'prometheus/v1', 'service' => $file->service, 'labels' => ['generated_by' => 'slo-kit'], 'slos' => $slos];
    }

    /**
     * Route templates with * as a PromQL (RE2) regex, escaped for a double-quoted string.
     *
     * @param list<string> $routes
     */
    public static function routeRegex(array $routes): string
    {
        $parts = [];
        foreach ($routes as $route) {
            $regex = '';
            foreach (str_split($route) as $char) {
                $regex .= match (true) {
                    $char === '*' => '.*',
                    ctype_alnum($char) || \in_array($char, ['_', '-', '/', ' ', ':'], true) => $char,
                    default => '\\\\' . $char,
                };
            }
            $parts[] = $regex;
        }

        return implode('|', $parts);
    }

    /**
     * @param list<int|string> $statuses
     */
    private static function codeRegex(array $statuses): string
    {
        return implode('|', array_map(static fn(int|string $s): string => \is_int($s) ? (string) $s : $s[0] . '..', $statuses));
    }

    private static function alertName(string $service, string $slo): string
    {
        // checkout + checkout-latency is CheckoutLatency, not CheckoutCheckoutLatency.
        $name = str_starts_with($slo, strtolower($service) . '-') ? $slo : $service . '-' . $slo;
        $words = preg_split('/[^a-zA-Z0-9]+/', $name) ?: [];

        return implode('', array_map(static fn(string $w): string => ucfirst(strtolower($w)), $words)) . 'BudgetBurn';
    }

    private static function number(float $value): string
    {
        return rtrim(rtrim(number_format($value, 6, '.', ''), '0'), '.');
    }
}
